import { StyleSheet, Platform } from 'react-native';
import { mergeThemes, getFontFamily } from '../utils';
// Create styles based on theme
export const createStyles = (theme) => {
    const mergedTheme = mergeThemes(theme);
    const fontFamily = getFontFamily();
    return StyleSheet.create({
        container: {
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: mergedTheme.background,
            zIndex: 9999,
        },
        headerContainer: {
            paddingTop: Platform.OS === 'android' ? 20 : 0,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            backgroundColor: '#0a0a0a',
            position: 'relative',
            overflow: 'hidden',
        },
        matrixBackground: {
            position: 'absolute',
            top: 0,
            right: 16,
            bottom: 0,
            justifyContent: 'center',
            alignItems: 'flex-end',
            opacity: 0.3,
            zIndex: 0,
        },
        matrixText: {
            color: mergedTheme.primary,
            fontSize: 12,
            fontFamily,
            fontWeight: '300',
            letterSpacing: 2,
        },
        header: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: 12,
            paddingHorizontal: 16,
            zIndex: 1,
        },
        terminalHeader: {
            flexDirection: 'row',
            alignItems: 'center',
        },
        terminalPrompt: {
            color: mergedTheme.primary,
            fontSize: 14,
            fontFamily,
            fontWeight: '600',
            marginRight: 4,
        },
        headerText: {
            color: mergedTheme.text,
            fontSize: 17,
            fontWeight: '600',
            letterSpacing: 0.5,
            fontFamily,
            textShadowColor: `${mergedTheme.primary}50`,
            textShadowOffset: { width: 0, height: 0 },
            textShadowRadius: 4,
        },
        cursor: {
            color: mergedTheme.primary,
            fontSize: 17,
            fontWeight: '300',
            opacity: 1,
        },
        closeButton: {
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: 3,
            backgroundColor: '#1a1a1a',
            borderWidth: 1,
            borderColor: mergedTheme.error,
        },
        closeButtonText: {
            color: mergedTheme.error,
            fontSize: 12,
            fontWeight: '700',
            fontFamily,
            letterSpacing: 0.5,
        },
        tabContainer: {
            flexDirection: 'row',
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            backgroundColor: mergedTheme.surface,
        },
        tab: {
            flex: 1,
            paddingVertical: 12,
            alignItems: 'center',
            justifyContent: 'center',
        },
        activeTab: {
            borderBottomWidth: 2,
            borderBottomColor: mergedTheme.primary,
            backgroundColor: '#1f1f1f',
        },
        tabText: {
            color: '#888',
            fontSize: 15,
            fontWeight: '500',
            letterSpacing: 0.3,
        },
        activeTabText: {
            color: mergedTheme.primary,
            fontWeight: '600',
        },
        actionsContainer: {
            flexDirection: 'column',
            justifyContent: 'flex-end',
            padding: 8,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            backgroundColor: mergedTheme.surface,
        },
        clearButton: {
            backgroundColor: '#3a3a3a',
            paddingVertical: 10,
            paddingHorizontal: 14,
            borderRadius: 6,
            minHeight: 40,
            alignItems: 'center',
            justifyContent: 'center',
            borderWidth: 1,
            borderColor: '#4a4a4a',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.15,
            shadowRadius: 1.5,
            elevation: 1,
        },
        clearButtonText: {
            color: '#e8e8e8',
            fontSize: 13,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        searchBar: {
            backgroundColor: '#2a2a2a',
            paddingVertical: 10,
            paddingHorizontal: 14,
            borderRadius: 8,
            marginTop: 8,
            color: mergedTheme.text,
            flex: 1,
            fontSize: 14,
            fontWeight: '500',
            borderWidth: 1,
            borderColor: '#3a3a3a',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.15,
            shadowRadius: 1.5,
            elevation: 1,
        },
        logsContainer: {
            flex: 1,
        },
        logItem: {
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            backgroundColor: mergedTheme.surface,
            marginHorizontal: 0,
            marginVertical: 0,
            marginBottom: 4,
        },
        logHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            marginBottom: 8,
            alignItems: 'center',
        },
        methodContainer: {
            borderRadius: 3,
            paddingVertical: 2,
            paddingHorizontal: 6,
            backgroundColor: '#252525',
        },
        method: {
            fontWeight: '700',
            fontSize: 11,
            letterSpacing: 0.2,
        },
        methodGet: {
            color: mergedTheme.primary,
        },
        methodPost: {
            color: mergedTheme.primary,
        },
        methodPut: {
            color: '#FF9800',
        },
        methodDelete: {
            color: mergedTheme.error,
        },
        methodPatch: {
            color: '#9C27B0',
        },
        methodOther: {
            color: '#9E9E9E',
        },
        statusContainer: {
            borderRadius: 3,
            paddingVertical: 2,
            paddingHorizontal: 6,
            backgroundColor: '#252525',
        },
        status: {
            fontWeight: '700',
            fontSize: 11,
            letterSpacing: 0.2,
        },
        successStatus: {
            color: mergedTheme.primary,
        },
        errorStatus: {
            color: mergedTheme.error,
        },
        url: {
            color: '#e8e8e8',
            fontSize: 12,
            marginBottom: 8,
            fontFamily,
            lineHeight: 16,
            fontWeight: '400',
        },
        logFooter: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingTop: 6,
        },
        time: {
            color: '#a8a8a8',
            fontSize: 10,
            fontWeight: '600',
            fontFamily,
        },
        timestamp: {
            color: '#888',
            fontSize: 10,
            fontFamily,
            fontWeight: '500',
        },
        viewDetailsText: {
            color: mergedTheme.primary,
            fontSize: 10,
            fontWeight: '600',
            letterSpacing: 0.2,
        },
        emptyContainer: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingTop: 80,
            paddingHorizontal: 32,
            flex: 1,
        },
        emptyText: {
            color: '#a8a8a8',
            fontSize: 16,
            textAlign: 'center',
            marginBottom: 8,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        emptySubtext: {
            color: '#757575',
            fontSize: 13,
            textAlign: 'center',
            lineHeight: 18,
            marginBottom: 16,
            opacity: 0.8,
        },
        detailContainerWrapper: {
            flex: 1,
            backgroundColor: mergedTheme.background,
        },
        detailContainer: {
            flex: 1,
            padding: 12,
        },
        detailHeader: {
            marginBottom: 16,
            backgroundColor: '#1f1f1f',
            borderRadius: 8,
            padding: 12,
            borderWidth: 1,
            borderColor: mergedTheme.border,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        topBackButtonContainer: {
            marginBottom: 12,
            alignSelf: 'flex-start',
        },
        topBackButtonText: {
            color: mergedTheme.primary,
            fontSize: 15,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        backButton: {
            marginBottom: 12,
        },
        backButtonText: {
            color: mergedTheme.primary,
            fontSize: 16,
        },
        detailTitleContainer: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            marginBottom: 16,
        },
        methodBadge: {
        // Inherits from statusRowBadge for consistent height
        },
        methodBadgeText: {
            fontWeight: '700',
            fontSize: 13,
            letterSpacing: 0.4,
            textAlign: 'center',
            lineHeight: 16,
            includeFontPadding: false,
        },
        detailTitle: {
            color: '#E6EDF3',
            fontSize: 13,
            fontWeight: '500',
            fontFamily,
            lineHeight: 18,
        },
        detailSection: {
            marginBottom: 12,
        },
        sectionTitle: {
            color: '#E6EDF3',
            fontSize: 15,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        subsectionTitle: {
            color: mergedTheme.primary,
            fontSize: 14,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        detailCard: {
            backgroundColor: '#1f1f1f',
            borderRadius: 6,
            padding: 12,
            borderWidth: 1,
            borderColor: mergedTheme.border,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.2,
            shadowRadius: 2,
            elevation: 2,
        },
        errorCard: {
            borderLeftWidth: 4,
            borderLeftColor: mergedTheme.error,
            backgroundColor: '#2a1f1f',
        },
        detailRow: {
            flexDirection: 'row',
            marginBottom: 8,
            paddingBottom: 8,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
        },
        detailLabel: {
            color: '#a8a8a8',
            fontSize: 13,
            width: 90,
            fontWeight: '600',
            marginRight: 10,
        },
        detailValue: {
            color: '#E6EDF3',
            fontSize: 13,
            fontFamily,
            lineHeight: 18,
        },
        codeScrollContainer: {
            marginVertical: 6,
            backgroundColor: '#252525',
            padding: 10,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: mergedTheme.border,
        },
        jsonText: {
            color: '#E6EDF3',
            fontFamily,
            fontSize: 12,
            lineHeight: 16,
            flexShrink: 1,
        },
        errorText: {
            color: mergedTheme.error,
        },
        infoCard: {
            backgroundColor: '#1f1f1f',
            borderRadius: 12,
            margin: 12,
            marginBottom: 16,
            overflow: 'hidden',
            borderWidth: 1,
            borderColor: mergedTheme.border,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        infoHeader: {
            padding: 16,
            backgroundColor: '#252525',
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
        },
        infoHeaderText: {
            color: mergedTheme.text,
            fontSize: 16,
            fontWeight: '700',
            letterSpacing: 0.5,
        },
        infoHeaderIcon: {
            width: 20,
            height: 20,
            tintColor: mergedTheme.primary,
        },
        infoContainer: {
            padding: 16,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            flexDirection: 'row',
            alignItems: 'flex-start',
            minHeight: 50,
        },
        infoLabel: {
            color: '#a8a8a8',
            fontSize: 14,
            width: 120,
            fontWeight: '600',
            marginRight: 16,
            paddingTop: 2,
        },
        infoValue: {
            color: '#e8e8e8',
            fontSize: 14,
            flex: 1,
            lineHeight: 20,
            fontWeight: '400',
        },
        subsectionHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: 10,
            paddingBottom: 6,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
        },
        copyButton: {
            backgroundColor: '#2a2a2a',
            paddingVertical: 4,
            paddingHorizontal: 8,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.15,
            shadowRadius: 1.5,
            elevation: 1,
        },
        copyButtonText: {
            color: mergedTheme.primary,
            fontSize: 12,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        actionButton: {
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: 8,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: 120,
            backgroundColor: '#2a2a2a',
            borderWidth: 1,
            borderColor: '#3a3a3a',
            margin: 12,
            marginBottom: 8,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.22,
            shadowRadius: 2.22,
            elevation: 3,
        },
        actionButtonText: {
            color: '#E6EDF3',
            fontSize: 14,
            fontWeight: '600',
            textAlign: 'center',
            letterSpacing: 0.3,
        },
        actionButtonTextDanger: {
            color: mergedTheme.error,
            fontSize: 14,
            fontWeight: '700',
            letterSpacing: 0.3,
        },
        actionButtonPrimary: {
            backgroundColor: mergedTheme.primary,
            borderColor: mergedTheme.primary,
        },
        actionButtonPrimaryText: {
            color: 'white',
        },
        actionButtonDanger: {
            backgroundColor: '#3d1a1a',
            borderColor: mergedTheme.error,
        },
        storageKeyText: {
            color: '#d4d4d4',
            fontSize: 13,
            fontFamily,
            backgroundColor: '#252525',
            padding: 8,
            borderRadius: 6,
            marginVertical: 2,
            borderLeftWidth: 3,
            borderLeftColor: mergedTheme.primary,
        },
        storageKeysContainer: {
            maxHeight: 200,
            paddingHorizontal: 16,
            paddingBottom: 8,
        },
        infoValueHighlight: {
            color: mergedTheme.primary,
            fontWeight: '600',
        },
        infoValueSuccess: {
            color: mergedTheme.success,
            fontWeight: '600',
        },
        infoValueWarning: {
            color: mergedTheme.warning,
            fontWeight: '600',
        },
        infoValueError: {
            color: mergedTheme.error,
            fontWeight: '600',
        },
        emptyStateContainer: {
            alignItems: 'center',
            justifyContent: 'center',
            padding: 32,
        },
        emptyStateIcon: {
            fontSize: 48,
            color: '#4a4a4a',
            marginBottom: 12,
        },
        emptyStateText: {
            color: '#8a8a8a',
            fontSize: 16,
            textAlign: 'center',
            marginBottom: 4,
            fontWeight: '500',
        },
        statsContainer: {
            backgroundColor: '#252525',
            paddingVertical: 8,
            borderBottomWidth: 1,
            borderBottomColor: mergedTheme.border,
            borderRadius: 8,
            marginBottom: 6,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.2,
            shadowRadius: 2,
            elevation: 2,
        },
        statsRow: {
            flexDirection: 'row',
            paddingHorizontal: 12,
            alignItems: 'center',
            justifyContent: 'space-evenly',
            minHeight: 40,
        },
        statItem: {
            alignItems: 'center',
            justifyContent: 'center',
            paddingHorizontal: 6,
            minWidth: 50,
            height: 36,
        },
        statValue: {
            color: mergedTheme.text,
            fontSize: 13,
            fontWeight: '700',
            fontFamily,
            marginBottom: 2,
            textAlign: 'center',
            lineHeight: 16,
        },
        statLabel: {
            color: '#b8b8b8',
            fontSize: 9,
            fontWeight: '600',
            textTransform: 'uppercase',
            letterSpacing: 0.4,
            textAlign: 'center',
            lineHeight: 12,
        },
        statDivider: {
            width: 1,
            height: 24,
            backgroundColor: '#4a4a4a',
            alignSelf: 'center',
        },
        successText: {
            color: mergedTheme.primary,
        },
        repeatRequestButton: {
            backgroundColor: mergedTheme.primary,
            padding: 12,
            borderRadius: 8,
            alignItems: 'center',
            marginTop: 10,
        },
        repeatRequestButtonDisabled: {
            backgroundColor: '#2a2a2a',
        },
        repeatRequestButtonText: {
            color: 'white',
            fontSize: 14,
            fontWeight: '600',
        },
        statusFilterContainer: {
            flexDirection: 'row',
            marginTop: 4,
            paddingHorizontal: 0,
            flexWrap: 'wrap',
            gap: 6,
        },
        statusFilterButton: {
            backgroundColor: '#2a2a2a',
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.1,
            shadowRadius: 1,
            elevation: 1,
        },
        statusFilterButtonActive: {
            backgroundColor: mergedTheme.primary,
            borderColor: mergedTheme.primary,
            shadowOpacity: 0.2,
        },
        statusFilterText: {
            color: '#b8b8b8',
            fontSize: 11,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        statusFilterTextActive: {
            color: 'white',
            fontWeight: '700',
        },
        urlContainer: {
            flex: 1,
            backgroundColor: '#252525',
            padding: 10,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: mergedTheme.border,
            marginBottom: 12,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.2,
            shadowRadius: 2,
            elevation: 2,
        },
        copyUrlHint: {
            color: mergedTheme.primary,
            fontSize: 11,
            marginTop: 4,
            opacity: 0.8,
            fontWeight: '500',
        },
        summaryActions: {
            flexDirection: 'row',
            justifyContent: 'center',
        },
        repeatButton: {
            backgroundColor: '#2a2a2a',
            borderColor: '#3a3a3a',
        },
        floatingControls: {
            position: 'absolute',
            bottom: 20,
            right: 12,
            flexDirection: 'row',
            gap: 10,
        },
        floatingBackButton: {
            backgroundColor: '#2a2a2a',
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: mergedTheme.primary,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        floatingBackButtonText: {
            color: mergedTheme.primary,
            fontWeight: '600',
            fontSize: 13,
            letterSpacing: 0.3,
        },
        floatingScrollTopButton: {
            backgroundColor: '#2a2a2a',
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: mergedTheme.primary,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 5,
        },
        floatingScrollTopButtonText: {
            color: mergedTheme.primary,
            fontWeight: '600',
            fontSize: 13,
            letterSpacing: 0.3,
        },
        collapsibleHeader: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: 12,
            backgroundColor: '#2a2a2a',
            borderBottomWidth: 1,
            borderBottomColor: '#3a3a3a',
            borderRadius: 8,
            marginBottom: 4,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.2,
            shadowRadius: 2,
            elevation: 2,
        },
        expandIcon: {
            color: mergedTheme.primary,
            fontSize: 16,
            fontWeight: '700',
            minWidth: 20,
            textAlign: 'center',
        },
        collapsibleContent: {
            padding: 12,
            backgroundColor: '#1a1a1a',
            borderRadius: 8,
            borderWidth: 1,
            borderColor: mergedTheme.border,
            marginBottom: 4,
        },
        statusRow: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 12,
            gap: 8,
            flexWrap: 'wrap',
        },
        statusRowBadge: {
            backgroundColor: '#2a2a2a',
            paddingVertical: 6,
            paddingHorizontal: 8,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            height: 32,
            justifyContent: 'center',
            alignItems: 'center',
        },
        statusText: {
            fontSize: 13,
            fontWeight: '700',
            fontFamily,
            textAlign: 'center',
            lineHeight: 16,
            includeFontPadding: false,
        },
        timeText: {
            fontSize: 12,
            color: '#a8a8a8',
            fontFamily,
            fontWeight: '500',
            textAlign: 'center',
            lineHeight: 14,
            includeFontPadding: false,
        },
        durationText: {
            fontSize: 12,
            color: mergedTheme.primary,
            fontFamily,
            fontWeight: '600',
            textAlign: 'center',
            lineHeight: 14,
            includeFontPadding: false,
        },
        controlsBar: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: 10,
            marginBottom: 4,
        },
        controlButton: {
            paddingVertical: 10,
            paddingHorizontal: 14,
            borderRadius: 6,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            backgroundColor: '#2a2a2a',
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            minHeight: 40,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.15,
            shadowRadius: 1.5,
            elevation: 1,
        },
        searchToggleButton: {
            flex: 1,
            marginRight: 12,
            justifyContent: 'flex-start',
            paddingLeft: 16,
            position: 'relative',
        },
        controlButtonText: {
            color: '#e8e8e8',
            fontSize: 13,
            fontWeight: '600',
            letterSpacing: 0.3,
        },
        activeIndicator: {
            position: 'absolute',
            top: 6,
            right: 6,
            width: 6,
            height: 6,
            borderRadius: 3,
            backgroundColor: mergedTheme.primary,
        },
        searchSection: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: '#2a2a2a',
            borderRadius: 8,
            borderWidth: 1,
            borderColor: '#3a3a3a',
            marginBottom: 6,
            shadowColor: '#000',
            shadowOffset: {
                width: 0,
                height: 1,
            },
            shadowOpacity: 0.15,
            shadowRadius: 1.5,
            elevation: 1,
        },
        searchInput: {
            flex: 1,
            paddingVertical: 12,
            paddingHorizontal: 16,
            color: mergedTheme.text,
            fontSize: 14,
            fontWeight: '400',
        },
        clearSearchButton: {
            padding: 8,
            marginRight: 8,
            backgroundColor: '#3a3a3a',
            borderRadius: 4,
            borderWidth: 1,
            borderColor: '#4a4a4a',
        },
        clearSearchText: {
            color: '#888',
            fontSize: 12,
            fontWeight: '600',
        },
        // Missing Developer Console styles
        headerTitle: {
            color: mergedTheme.text,
            fontSize: 18,
            fontWeight: '700',
            letterSpacing: 0.5,
        },
        tabBadge: {
            color: mergedTheme.primary,
            fontSize: 12,
        },
        content: {
            flex: 1,
            backgroundColor: mergedTheme.background,
        },
        // General Info Panel styles
        generalContainer: {
            flex: 1,
            padding: 16,
        },
        // Status filter styles that were missing
        statusFilterChip: {
            paddingHorizontal: 12,
            paddingVertical: 6,
            borderRadius: 16,
            backgroundColor: '#2a2a2a',
            borderWidth: 1,
            borderColor: '#3a3a3a',
            marginRight: 8,
        },
        statusFilterChipActive: {
            backgroundColor: mergedTheme.primary,
            borderColor: mergedTheme.primary,
        },
        statusFilterChipText: {
            color: '#888',
            fontSize: 12,
            fontWeight: '600',
        },
        statusFilterChipTextActive: {
            color: '#000',
        },
        emptySubText: {
            color: '#666',
            fontSize: 14,
            textAlign: 'center',
            marginTop: 8,
        },
        // Missing infoRow style
        infoRow: {
            flexDirection: 'row',
            justifyContent: 'space-between',
            alignItems: 'center',
            paddingVertical: 8,
            borderBottomWidth: 1,
            borderBottomColor: '#2a2a2a',
        },
        // Missing infoSection style
        infoSection: {
            backgroundColor: '#1a1a1a',
            borderRadius: 8,
            padding: 16,
            marginBottom: 16,
            borderWidth: 1,
            borderColor: mergedTheme.border,
        },
    });
};
// Export default styles function
export default createStyles;
