import { ThemeConfig } from '../types';
export declare const getMethodStyle: (method: string, styles: any) => any;
export declare const formatValue: (value: any) => string;
export declare const getStatusIndicator: (status: number | null) => string;
export declare const getDurationColor: (duration: number | null) => string;
export declare const getValueStyle: (value: any, isStatus?: boolean) => "default" | "error" | "success" | "warning" | "highlight";
export declare const mergeThemes: (theme?: ThemeConfig) => Required<ThemeConfig>;
export declare const getFontFamily: () => "Menlo" | "monospace";
export declare const formatTimestamp: (timestamp: number) => string;
export declare const formatDate: (timestamp: number) => string;
export declare const truncateText: (text: string, maxLength: number) => string;
export declare const isDevelopment: () => boolean;
export declare const isStaging: () => boolean;
export declare const safeJsonParse: (text: string, fallback?: any) => any;
export declare const copyToClipboard: (text: string) => Promise<boolean>;
export declare const getDeviceInfo: () => Promise<{
    appVersion: any;
    buildNumber: any;
    bundleId: any;
    firstInstallTime: string;
    deviceId: any;
    deviceModel: any;
    systemName: any;
    systemVersion: any;
    manufacturer: any;
    totalMemory: number;
    batteryLevel: number;
    isEmulator: any;
} | null>;
export declare const getStorageKeys: () => Promise<string[]>;
export declare const clearStorage: () => Promise<boolean>;
